/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oFMww5CfyAzvgggjKwbJid
// Component: BJzIebU9mBl1

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button from "../../Button"; // plasmic-import: oVzoHzMf1TLl/component
import { SideEffect } from "@plasmicpkgs/plasmic-basic-components";
import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: oFMww5CfyAzvgggjKwbJid/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: oFMww5CfyAzvgggjKwbJid/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: oFMww5CfyAzvgggjKwbJid/projectcss
import sty from "./PlasmicFactorPrint.module.css"; // plasmic-import: BJzIebU9mBl1/css

import ChevronRightIcon from "../fragment_icons/icons/PlasmicIcon__ChevronRight"; // plasmic-import: GHdF3hS-oP_3/icon
import ChevronLeftIcon from "../fragment_icons/icons/PlasmicIcon__ChevronLeft"; // plasmic-import: r9Upp9NbiZkf/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: HwRbVpdez4ob/icon

createPlasmicElementProxy;

export type PlasmicFactorPrint__VariantMembers = {};
export type PlasmicFactorPrint__VariantsArgs = {};
type VariantPropType = keyof PlasmicFactorPrint__VariantsArgs;
export const PlasmicFactorPrint__VariantProps = new Array<VariantPropType>();

export type PlasmicFactorPrint__ArgsType = {};
type ArgPropType = keyof PlasmicFactorPrint__ArgsType;
export const PlasmicFactorPrint__ArgProps = new Array<ArgPropType>();

export type PlasmicFactorPrint__OverridesType = {
  factorPrint?: Flex__<"div">;
  holderPrint?: Flex__<"section">;
  sideEffect?: Flex__<typeof SideEffect>;
  embedHtml?: Flex__<typeof Embed>;
  svg?: Flex__<"svg">;
};

export interface DefaultFactorPrintProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicFactorPrint__RenderFunc(props: {
  variants: PlasmicFactorPrint__VariantsArgs;
  args: PlasmicFactorPrint__ArgsType;
  overrides: PlasmicFactorPrint__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const $globalActions = useGlobalActions?.();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "factorDetails",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => ({})
      },
      {
        path: "customerDetails",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => ({})
      },
      {
        path: "waiting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => true
      },
      {
        path: "isPrint",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicFactorPrint.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicFactorPrint.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicFactorPrint.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"factorPrint"}
          data-plasmic-override={overrides.factorPrint}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.factorPrint,
            ``
          )}
        >
          <section
            data-plasmic-name={"holderPrint"}
            data-plasmic-override={overrides.holderPrint}
            className={classNames(projectcss.all, sty.holderPrint)}
            id={"holderPrint"}
          >
            <div className={classNames(projectcss.all, sty.freeBox__ggHAg)}>
              <div className={classNames(projectcss.all, sty.freeBox__l7Tek)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__uBlhC)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"50px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/katibe_nelson/images/logo5E03Fe79Svg.svg",
                    fullWidth: 102.473,
                    fullHeight: 108.85,
                    aspectRatio: 0.941415
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__tHpE)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___0M6Zq
                  )}
                >
                  <React.Fragment>
                    {(() => {
                      try {
                        return (
                          ($state.factorDetails.data.meta.payment_status ==
                            undefined ||
                          $state.factorDetails.data.meta.payment_status ==
                            "unpaid"
                            ? "پیش فاکتور "
                            : "") + $state.factorDetails.data.title
                        ).replaceAll("فاکتور فاکتور", "فاکتور");
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "\u0635\u0648\u0631\u062a \u062d\u0633\u0627\u0628 \u0641\u0631\u0648\u0634 \u06a9\u0627\u0644\u0627 \u0648 \u062e\u062f\u0645\u0627\u062a \u0645\u0647\u0631 1403";
                        }
                        throw e;
                      }
                    })()}
                  </React.Fragment>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__cwgq)}>
                <div className={classNames(projectcss.all, sty.freeBox__argMn)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__jaHli)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___9LgNr
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__ih55Y
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__yCsIo
                          )}
                        >
                          {
                            "\u0634\u0645\u0627\u0631\u0647 \u0641\u0627\u06a9\u062a\u0648\u0631:"
                          }
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___5Y7Qz
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__xXkJg
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return $state.factorDetails.data.factorid;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "1324";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__aNnq1)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__uGkYl
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___1HkKy
                          )}
                        >
                          {"\u062a\u0627\u0631\u06cc\u062e:"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__hhQys
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__xdxd6
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return (() => {
                                  const gregorianDate = new Date(
                                    $state.factorDetails.data.registerdate
                                  );
                                  const persianDate = new Intl.DateTimeFormat(
                                    "fa-IR"
                                  ).format(gregorianDate);
                                  return persianDate;
                                })();
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "1403/11/05";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__nddt7)}>
              <div className={classNames(projectcss.all, sty.freeBox__xZ7P)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___0UvQr)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox___50RmZ)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__dzGby)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__lmT83
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__xiccG
                          )}
                        >
                          {
                            "\u0634\u0645\u0627\u0631\u0647 \u0641\u0627\u06a9\u062a\u0648\u0631:"
                          }
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__qFpwb
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return $ctx.query.factorid;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "1324";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__q3Fe7
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__de9Eq
                          )}
                        >
                          {"\u062a\u0627\u0631\u06cc\u062e:"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__el9Kp
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return (() => {
                                  const gregorianDate = new Date(
                                    $state.factorDetails.data.registerdate
                                  );
                                  const persianDate = new Intl.DateTimeFormat(
                                    "fa-IR"
                                  ).format(gregorianDate);
                                  return persianDate;
                                })();
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "1403/11/05";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__fX8RT)}>
              <div className={classNames(projectcss.all, sty.freeBox___0RqiL)}>
                <div className={classNames(projectcss.all, sty.freeBox__hNii)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___53OT)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__m9Tt
                      )}
                    >
                      {
                        "\u0645\u0634\u062e\u0635\u0627\u062a \u0641\u0631\u0648\u0634\u0646\u062f\u0647"
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__j9SJk)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__aEaf9)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__wjAJq
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___5BZz6
                          )}
                        >
                          {
                            "\u0646\u0627\u0645: \u0633\u067e\u0647\u0631 \u0633\u0644\u0627\u0645\u062a \u06a9\u0648\u06cc\u0631 \u0627\u06cc\u0633\u0627\u062a\u06cc\u0633"
                          }
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___6Mj6Q
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__pf49H
                          )}
                        >
                          {
                            "\u06a9\u062f \u0627\u0642\u062a\u0635\u0627\u062f\u06cc: 14005241283"
                          }
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__obxUz
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___5Y5KF
                          )}
                        >
                          {
                            "\u0634\u0645\u0627\u0631\u0647 \u062b\u0628\u062a: 15708"
                          }
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__igyHi
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__enz6P
                          )}
                        >
                          {
                            "\u0634\u0646\u0627\u0633\u0647 \u0645\u0644\u06cc: 14005241283"
                          }
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox___01Me)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__lIlWz
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ffaHq
                          )}
                        >
                          {" \u06a9\u062f\u067e\u0633\u062a\u06cc: 8917697998"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__vpCxl
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__grdj7
                          )}
                        >
                          {" \u062a\u0644\u0641\u0646: 36286033"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__qGuCg
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__vOxv
                          )}
                        >
                          {
                            "\u0622\u062f\u0631\u0633: \u06cc\u0632\u062f - \u062e\u06cc\u0627\u0628\u0627\u0646 \u0645\u0637\u0647\u0631\u06cc - \u067e\u0644\u0627\u06a9 \u06f1\u06f0\u06f8 - \u067e\u0627\u0631\u06a9 \u0639\u0644\u0645 \u0648 \u0641\u0646\u0627\u0648\u0631\u06cc \u06cc\u0632\u062f"
                          }
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___4FzQl
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__dYUm0
                          )}
                        >
                          {" \u0641\u06a9\u0633:"}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__aFrnn)}>
              <div className={classNames(projectcss.all, sty.freeBox__kStuM)}>
                <div className={classNames(projectcss.all, sty.freeBox__r9Cf0)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__mWvOz)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lyWnv
                      )}
                    >
                      {
                        "\u0645\u0634\u062e\u0635\u0627\u062a \u062e\u0631\u06cc\u062f\u0627\u0631"
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__t6Xm8)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__aojzh)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__aDk6F
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__sWqN
                          )}
                        >
                          {"\u0646\u0627\u0645: "}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__gIuS8
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return $state.customerDetails.data.name;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__r2JoU
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__g7QVu
                          )}
                        >
                          {
                            "\u06a9\u062f \u0627\u0642\u062a\u0635\u0627\u062f\u06cc: "
                          }
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__fXFkI
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return $state.customerDetails.data
                                  .economic_code;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "\u06a9\u062f \u0627\u0642\u062a\u0635\u0627\u062f\u06cc: ";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__rxz60
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__fbFH
                          )}
                        >
                          {
                            "\u0634\u0645\u0627\u0631\u0647 \u062b\u0628\u062a: "
                          }
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zlwg3
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return $state.customerDetails.data
                                  .registration_number;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "\u0634\u0645\u0627\u0631\u0647 \u062b\u0628\u062a: ";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__lVwAg)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__yWyRr
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__dsdbO
                          )}
                        >
                          {
                            "\u0634\u0646\u0627\u0633\u0647 \u0645\u0644\u06cc: "
                          }
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__nFPxx
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return $state.customerDetails.data.national_id;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "\u0634\u0646\u0627\u0633\u0647 \u0645\u0644\u06cc: ";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__xmLla
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__hKB
                          )}
                        >
                          {" \u06a9\u062f\u067e\u0633\u062a\u06cc: "}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___1QjH3
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return $state.customerDetails.data.postal_code;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return " \u06a9\u062f\u067e\u0633\u062a\u06cc: ";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__qiep
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zlc6X
                          )}
                        >
                          {" \u062a\u0644\u0641\u0646: "}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__qToa0
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return $state.customerDetails.data.phone;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return " \u062a\u0644\u0641\u0646: ";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__rYa74
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wd1E3
                          )}
                        >
                          {"\u0622\u062f\u0631\u0633: "}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__vAr5
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return $state.customerDetails.data.address;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "\u0646\u0634\u0627\u0646\u06cc: ";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__w6Y4Q
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__dWfaK
                          )}
                        >
                          {" \u0641\u06a9\u0633:"}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__ywq0M)}>
              <div className={classNames(projectcss.all, sty.freeBox__gA6J2)}>
                <div className={classNames(projectcss.all, sty.freeBox__z3UhB)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__mx64)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__evhC2
                      )}
                    >
                      {
                        "\u0645\u0634\u062e\u0635\u0627\u062a \u06a9\u0627\u0644\u0627 \u0648 \u062e\u062f\u0645\u0627\u062a"
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__k5PhA)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__oYwfu)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__rI7Ff
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__dC3F
                          )}
                        >
                          {"\u0631\u062f\u06cc\u0641"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___9DSyA
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__prQv
                          )}
                        >
                          {"\u0639\u0646\u0648\u0627\u0646"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___5XuYk
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__tt7TN
                          )}
                        >
                          {"\u062a\u0639\u062f\u0627\u062f"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__nKjA
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__o9Hwn
                          )}
                        >
                          {hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "\u0645\u0628\u0644\u063a"
                            : "\u0645\u0628\u0644\u063a \u0647\u0631 \u0648\u0627\u062d\u062f (\u0631\u06cc\u0627\u0644)"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__lDjtV
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___9O1Lw
                          )}
                        >
                          {hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "\u062c\u0645\u0639"
                            : "\u062c\u0645\u0639 (\u0631\u06cc\u0627\u0644)"}
                        </div>
                      </div>
                    </div>
                    {(_par =>
                      !_par ? [] : Array.isArray(_par) ? _par : [_par])(
                      (() => {
                        try {
                          return $state.factorDetails.data.services;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return [];
                          }
                          throw e;
                        }
                      })()
                    ).map((__plasmic_item_0, __plasmic_idx_0) => {
                      const currentItem = __plasmic_item_0;
                      const currentIndex = __plasmic_idx_0;
                      return (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__iTIb
                          )}
                          key={currentIndex}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___4Tcoc
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__rie6H
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return currentIndex + 1;
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return "\u0631\u062f\u06cc\u0641";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__r1AJm
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__p5Y6E
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return currentItem.service;
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return "\u0639\u0646\u0648\u0627\u0646";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__o45HS
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__mpxRk
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return new Intl.NumberFormat(
                                      "fa-IR"
                                    ).format(currentItem.count);
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return "\u062a\u0639\u062f\u0627\u062f";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__tGIaZ
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___79AF
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return new Intl.NumberFormat(
                                      "fa-IR"
                                    ).format(currentItem.price);
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return "\u0645\u0628\u0644\u063a \u0647\u0631 \u0648\u0627\u062d\u062f (\u0631\u06cc\u0627\u0644)";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__bYiK
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__xbulf
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return new Intl.NumberFormat(
                                      "fa-IR"
                                    ).format(
                                      currentItem.price * currentItem.count
                                    );
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return "\u062c\u0645\u0639";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                          </div>
                        </div>
                      );
                    })}
                    <div
                      className={classNames(projectcss.all, sty.freeBox__fqAba)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__qYhvk
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__fvvJv
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return (
                                  "تخفیف: " +
                                  new Intl.NumberFormat("fa-IR").format(
                                    $state.factorDetails.data.discountprice
                                  ) +
                                  " ریال"
                                );
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___9WQ
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__qQmch
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return (
                                  "مالیات: " +
                                  new Intl.NumberFormat("fa-IR").format(
                                    $state.factorDetails.data.vatprice
                                  ) +
                                  " ریال"
                                );
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__nU6D
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__iiuua
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return (
                                  "قابل پرداخت: " +
                                  new Intl.NumberFormat("fa-IR").format(
                                    $state.factorDetails.data.finalprice
                                  ) +
                                  " ریال"
                                );
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__yOyc)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__yjR8H
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__afIpO
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return $state.factorDetails.data.description;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                        {(() => {
                          try {
                            return (
                              $state.factorDetails.data.due_date != undefined &&
                              $state.factorDetails.data.due_date.length > 0 &&
                              ($state.factorDetails.data.meta.payment_status ==
                                "unpaid" ||
                                $state.factorDetails.data.meta.payment_status ==
                                  undefined)
                            );
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return true;
                            }
                            throw e;
                          }
                        })() ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ryicD
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return (
                                    "مهلت پرداخت: " +
                                    (() => {
                                      const gregorianDate = new Date(
                                        $state.factorDetails.data.due_date
                                      );
                                      const persianDate =
                                        new Intl.DateTimeFormat("fa-IR").format(
                                          gregorianDate
                                        );
                                      return persianDate;
                                    })()
                                  );
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "\u0645\u0647\u0644\u062a \u067e\u0631\u062f\u0627\u062e\u062a: ";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </div>
                        ) : null}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__cFw6R)}>
              <div className={classNames(projectcss.all, sty.freeBox___2YhP8)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___2S4K
                  )}
                >
                  {
                    "\u0645\u0647\u0631 \u0648 \u0627\u0645\u0636\u0627\u06cc \u0641\u0631\u0648\u0634\u0646\u062f\u0647"
                  }
                </div>
                {(() => {
                  try {
                    return (
                      false &&
                      $state.factorDetails?.data?.meta?.payment_status &&
                      $state.factorDetails.data.meta.payment_status == "paid"
                    );
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return true;
                    }
                    throw e;
                  }
                })() ? (
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__z5Gkp)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"164px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/katibe_nelson/images/signPng.png",
                      fullWidth: 431,
                      fullHeight: 254,
                      aspectRatio: undefined
                    }}
                  />
                ) : null}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__kXvcm)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xbpR
                  )}
                >
                  {
                    "\u0645\u0647\u0631 \u0648 \u0627\u0645\u0636\u0627\u06cc \u062e\u0631\u06cc\u062f\u0627\u0631"
                  }
                </div>
              </div>
            </div>
            {(() => {
              try {
                return $state.isPrint;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div className={classNames(projectcss.all, sty.freeBox__tQTgi)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___8PSax)}
                >
                  <Button
                    children2={
                      "\u0686\u0627\u067e \u0641\u0627\u06a9\u062a\u0648\u0631"
                    }
                    className={classNames("__wab_instance", sty.button__rlSqv)}
                    color={"softBlue"}
                    onClick={async event => {
                      const $steps = {};

                      $steps["updateIsPrint"] = true
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["isPrint"]
                              },
                              operation: 0,
                              value: false
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;

                              $stateSet(objRoot, variablePath, value);
                              return value;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updateIsPrint"] != null &&
                        typeof $steps["updateIsPrint"] === "object" &&
                        typeof $steps["updateIsPrint"].then === "function"
                      ) {
                        $steps["updateIsPrint"] = await $steps["updateIsPrint"];
                      }

                      $steps["runCode"] = true
                        ? (() => {
                            const actionArgs = {
                              customFunction: async () => {
                                return window.print();
                              }
                            };
                            return (({ customFunction }) => {
                              return customFunction();
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["runCode"] != null &&
                        typeof $steps["runCode"] === "object" &&
                        typeof $steps["runCode"].then === "function"
                      ) {
                        $steps["runCode"] = await $steps["runCode"];
                      }

                      $steps["updateIsPrint2"] = true
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["isPrint"]
                              },
                              operation: 0,
                              value: true
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;

                              $stateSet(objRoot, variablePath, value);
                              return value;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updateIsPrint2"] != null &&
                        typeof $steps["updateIsPrint2"] === "object" &&
                        typeof $steps["updateIsPrint2"].then === "function"
                      ) {
                        $steps["updateIsPrint2"] =
                          await $steps["updateIsPrint2"];
                      }
                    }}
                  />
                </div>
              </div>
            ) : null}
          </section>
          {(() => {
            try {
              return !$state.waiting;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <section className={classNames(projectcss.all, sty.section__quhd3)}>
              <div className={classNames(projectcss.all, sty.freeBox__ezVh3)}>
                <div className={classNames(projectcss.all, sty.freeBox__koseg)}>
                  <Button
                    children2={
                      "\u0686\u0627\u067e \u0641\u0627\u06a9\u062a\u0648\u0631"
                    }
                    className={classNames("__wab_instance", sty.button__bfLXn)}
                    color={"softBlue"}
                    onClick={async event => {
                      const $steps = {};

                      $steps["runCode"] = true
                        ? (() => {
                            const actionArgs = {};
                            return (({ customFunction }) => {
                              return customFunction();
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["runCode"] != null &&
                        typeof $steps["runCode"] === "object" &&
                        typeof $steps["runCode"].then === "function"
                      ) {
                        $steps["runCode"] = await $steps["runCode"];
                      }
                    }}
                  />
                </div>
              </div>
            </section>
          ) : null}
          <SideEffect
            data-plasmic-name={"sideEffect"}
            data-plasmic-override={overrides.sideEffect}
            className={classNames("__wab_instance", sty.sideEffect)}
            deps={(() => {
              try {
                return [$ctx.query.factorid, $ctx.query.customertype];
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return undefined;
                }
                throw e;
              }
            })()}
            onMount={async () => {
              const $steps = {};

              $steps["getFactorDetails"] =
                $ctx.query.factorid > 0
                  ? (() => {
                      const actionArgs = {
                        args: [
                          undefined,
                          (() => {
                            try {
                              return (
                                "https://apigw.paziresh24.com/katibe/v1/factors/p24/" +
                                $ctx.query.factorid
                              );
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()
                        ]
                      };
                      return $globalActions["Fragment.apiRequest"]?.apply(
                        null,
                        [...actionArgs.args]
                      );
                    })()
                  : undefined;
              if (
                $steps["getFactorDetails"] != null &&
                typeof $steps["getFactorDetails"] === "object" &&
                typeof $steps["getFactorDetails"].then === "function"
              ) {
                $steps["getFactorDetails"] = await $steps["getFactorDetails"];
              }

              $steps["updateFactorDetails"] =
                $steps.getFactorDetails.status == 200
                  ? (() => {
                      const actionArgs = {
                        variable: {
                          objRoot: $state,
                          variablePath: ["factorDetails"]
                        },
                        operation: 0,
                        value: $steps.getFactorDetails.data
                      };
                      return (({
                        variable,
                        value,
                        startIndex,
                        deleteCount
                      }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;

                        $stateSet(objRoot, variablePath, value);
                        return value;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
              if (
                $steps["updateFactorDetails"] != null &&
                typeof $steps["updateFactorDetails"] === "object" &&
                typeof $steps["updateFactorDetails"].then === "function"
              ) {
                $steps["updateFactorDetails"] =
                  await $steps["updateFactorDetails"];
              }

              $steps["getCustomerDetails"] =
                $steps.getFactorDetails.status == 200
                  ? (() => {
                      const actionArgs = {
                        args: [
                          undefined,
                          (() => {
                            try {
                              return (
                                "https://apigw.paziresh24.com/financialaccount/v1/profiles" +
                                ($ctx.query.customertype == "center"
                                  ? "?centerid=" +
                                    $state.factorDetails.data.customerid
                                  : "")
                              );
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()
                        ]
                      };
                      return $globalActions["Fragment.apiRequest"]?.apply(
                        null,
                        [...actionArgs.args]
                      );
                    })()
                  : undefined;
              if (
                $steps["getCustomerDetails"] != null &&
                typeof $steps["getCustomerDetails"] === "object" &&
                typeof $steps["getCustomerDetails"].then === "function"
              ) {
                $steps["getCustomerDetails"] =
                  await $steps["getCustomerDetails"];
              }

              $steps["updateFactorDetails2"] =
                $steps.getCustomerDetails.status == 200
                  ? (() => {
                      const actionArgs = {
                        variable: {
                          objRoot: $state,
                          variablePath: ["customerDetails"]
                        },
                        operation: 0,
                        value: $steps.getCustomerDetails.data
                      };
                      return (({
                        variable,
                        value,
                        startIndex,
                        deleteCount
                      }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;

                        $stateSet(objRoot, variablePath, value);
                        return value;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
              if (
                $steps["updateFactorDetails2"] != null &&
                typeof $steps["updateFactorDetails2"] === "object" &&
                typeof $steps["updateFactorDetails2"].then === "function"
              ) {
                $steps["updateFactorDetails2"] =
                  await $steps["updateFactorDetails2"];
              }

              $steps["updateFactorDetails3"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["waiting"]
                      },
                      operation: 0,
                      value: false
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateFactorDetails3"] != null &&
                typeof $steps["updateFactorDetails3"] === "object" &&
                typeof $steps["updateFactorDetails3"].then === "function"
              ) {
                $steps["updateFactorDetails3"] =
                  await $steps["updateFactorDetails3"];
              }

              $steps["updateFactorDetails4"] = true
                ? (() => {
                    const actionArgs = {
                      customFunction: async () => {
                        return (() => {
                          return setTimeout(function () {}, 2000);
                        })();
                      }
                    };
                    return (({ customFunction }) => {
                      return customFunction();
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateFactorDetails4"] != null &&
                typeof $steps["updateFactorDetails4"] === "object" &&
                typeof $steps["updateFactorDetails4"].then === "function"
              ) {
                $steps["updateFactorDetails4"] =
                  await $steps["updateFactorDetails4"];
              }

              $steps["print"] =
                $steps.getFactorDetails.status == 200 &&
                $steps.getCustomerDetails.status == 200 &&
                $ctx.query.factorid > 0 &&
                $state.waiting == false
                  ? (() => {
                      const actionArgs = {
                        customFunction: async () => {
                          return window.print();
                        }
                      };
                      return (({ customFunction }) => {
                        return customFunction();
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
              if (
                $steps["print"] != null &&
                typeof $steps["print"] === "object" &&
                typeof $steps["print"].then === "function"
              ) {
                $steps["print"] = await $steps["print"];
              }
            }}
          />

          <Embed
            data-plasmic-name={"embedHtml"}
            data-plasmic-override={overrides.embedHtml}
            className={classNames("__wab_instance", sty.embedHtml)}
            code={
              '<script type="text/javascript">\r\n    (function(c,l,a,r,i,t,y){\r\n        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};\r\n        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;\r\n        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);\r\n    })(window, document, "clarity", "script", "pq37fqev3s");\r\n</script>'
            }
          />

          {(() => {
            try {
              return $state.waiting;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <section className={classNames(projectcss.all, sty.section__ghwv5)}>
              <Icon2Icon
                data-plasmic-name={"svg"}
                data-plasmic-override={overrides.svg}
                className={classNames(projectcss.all, sty.svg)}
                role={"img"}
              />
            </section>
          ) : null}
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  factorPrint: ["factorPrint", "holderPrint", "sideEffect", "embedHtml", "svg"],
  holderPrint: ["holderPrint"],
  sideEffect: ["sideEffect"],
  embedHtml: ["embedHtml"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  factorPrint: "div";
  holderPrint: "section";
  sideEffect: typeof SideEffect;
  embedHtml: typeof Embed;
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFactorPrint__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFactorPrint__VariantsArgs;
    args?: PlasmicFactorPrint__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicFactorPrint__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicFactorPrint__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFactorPrint__ArgProps,
          internalVariantPropNames: PlasmicFactorPrint__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFactorPrint__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "factorPrint") {
    func.displayName = "PlasmicFactorPrint";
  } else {
    func.displayName = `PlasmicFactorPrint.${nodeName}`;
  }
  return func;
}

export const PlasmicFactorPrint = Object.assign(
  // Top-level PlasmicFactorPrint renders the root element
  makeNodeComponent("factorPrint"),
  {
    // Helper components rendering sub-elements
    holderPrint: makeNodeComponent("holderPrint"),
    sideEffect: makeNodeComponent("sideEffect"),
    embedHtml: makeNodeComponent("embedHtml"),
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicFactorPrint
    internalVariantProps: PlasmicFactorPrint__VariantProps,
    internalArgProps: PlasmicFactorPrint__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "چاپ فاکتور",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicFactorPrint;
/* prettier-ignore-end */
