/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oFMww5CfyAzvgggjKwbJid
// Component: Nu0oYJ_Bbm-G

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { ApiRequest } from "@/fragment/components/api-request"; // plasmic-import: 1e0q7f6tCMQt/codeComponent
import Dialog from "../../Dialog"; // plasmic-import: FJiI2-N1is_F/component
import Button from "../../Button"; // plasmic-import: oVzoHzMf1TLl/component
import TransferToAnotherWallet from "../../TransferToAnotherWallet"; // plasmic-import: OwsFE4Jz_JMm/component
import Settlement from "../../Settlement"; // plasmic-import: 1Tzg-xPJwovd/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: oFMww5CfyAzvgggjKwbJid/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: oFMww5CfyAzvgggjKwbJid/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: oFMww5CfyAzvgggjKwbJid/projectcss
import sty from "./PlasmicFinancialReports.module.css"; // plasmic-import: Nu0oYJ_Bbm-G/css

import ChevronRightIcon from "../fragment_icons/icons/PlasmicIcon__ChevronRight"; // plasmic-import: GHdF3hS-oP_3/icon
import ChevronLeftIcon from "../fragment_icons/icons/PlasmicIcon__ChevronLeft"; // plasmic-import: r9Upp9NbiZkf/icon

createPlasmicElementProxy;

export type PlasmicFinancialReports__VariantMembers = {};
export type PlasmicFinancialReports__VariantsArgs = {};
type VariantPropType = keyof PlasmicFinancialReports__VariantsArgs;
export const PlasmicFinancialReports__VariantProps =
  new Array<VariantPropType>();

export type PlasmicFinancialReports__ArgsType = {
  centerId?: string;
  date?: string;
};
type ArgPropType = keyof PlasmicFinancialReports__ArgsType;
export const PlasmicFinancialReports__ArgProps = new Array<ArgPropType>(
  "centerId",
  "date"
);

export type PlasmicFinancialReports__OverridesType = {
  root?: Flex__<"div">;
  apiGetBookCount?: Flex__<typeof ApiRequest>;
  apiGetIncome?: Flex__<typeof ApiRequest>;
  apiGetbalance?: Flex__<typeof ApiRequest>;
  apiGetBalanceOnlineVisit?: Flex__<typeof ApiRequest>;
  apiGetTotalOnlineVisit?: Flex__<typeof ApiRequest>;
  apiGetTotal?: Flex__<typeof ApiRequest>;
  apiExpectedIncome?: Flex__<typeof ApiRequest>;
  bookcount?: Flex__<"div">;
  balance?: Flex__<"div">;
  dialogTransfer?: Flex__<typeof Dialog>;
  button?: Flex__<typeof Button>;
  transferToAnotherWallet?: Flex__<typeof TransferToAnotherWallet>;
  dialogSettlement?: Flex__<typeof Dialog>;
  btnSettlement?: Flex__<typeof Button>;
  settlement?: Flex__<typeof Settlement>;
  balance2?: Flex__<"div">;
  income?: Flex__<"div">;
  totalincome?: Flex__<"div">;
};

export interface DefaultFinancialReportsProps {
  centerId?: string;
  date?: string;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicFinancialReports__RenderFunc(props: {
  variants: PlasmicFinancialReports__VariantsArgs;
  args: PlasmicFinancialReports__ArgsType;
  overrides: PlasmicFinancialReports__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "apiGetBookCount.data",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiGetBookCount"
      },
      {
        path: "apiGetBookCount.error",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiGetBookCount"
      },
      {
        path: "apiGetBookCount.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiGetBookCount"
      },
      {
        path: "apiGetIncome.data",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiGetIncome"
      },
      {
        path: "apiGetIncome.error",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiGetIncome"
      },
      {
        path: "apiGetIncome.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiGetIncome"
      },
      {
        path: "apiGetbalance.data",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiGetbalance"
      },
      {
        path: "apiGetbalance.error",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiGetbalance"
      },
      {
        path: "apiGetbalance.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiGetbalance"
      },
      {
        path: "apiGetTotal.data",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiGetTotal"
      },
      {
        path: "apiGetTotal.error",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiGetTotal"
      },
      {
        path: "apiGetTotal.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiGetTotal"
      },
      {
        path: "apiGetBalanceOnlineVisit.data",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiGetBalanceOnlineVisit"
      },
      {
        path: "apiGetBalanceOnlineVisit.error",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiGetBalanceOnlineVisit"
      },
      {
        path: "apiGetBalanceOnlineVisit.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiGetBalanceOnlineVisit"
      },
      {
        path: "apiGetTotalOnlineVisit.data",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiGetTotalOnlineVisit"
      },
      {
        path: "apiGetTotalOnlineVisit.error",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiGetTotalOnlineVisit"
      },
      {
        path: "apiGetTotalOnlineVisit.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiGetTotalOnlineVisit"
      },
      {
        path: "apiExpectedIncome.data",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiExpectedIncome"
      },
      {
        path: "apiExpectedIncome.error",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiExpectedIncome"
      },
      {
        path: "apiExpectedIncome.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiExpectedIncome"
      },
      {
        path: "dialogTransfer.open",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "transferToAnotherWallet.transferCenterid",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $props.centerId == "5532" ? "" : $props.centerId;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      },
      {
        path: "transferToAnotherWallet.transferedCount",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "dialogSettlement.open",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <ApiRequest
        data-plasmic-name={"apiGetBookCount"}
        data-plasmic-override={overrides.apiGetBookCount}
        className={classNames("__wab_instance", sty.apiGetBookCount)}
        errorDisplay={
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__cYw1P
            )}
          >
            {"Error fetching data"}
          </div>
        }
        loadingDisplay={null}
        method={"GET"}
        onError={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["apiGetBookCount", "error"]).apply(
            null,
            eventArgs
          );
        }}
        onLoading={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, [
            "apiGetBookCount",
            "loading"
          ]).apply(null, eventArgs);
        }}
        onSuccess={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["apiGetBookCount", "data"]).apply(
            null,
            eventArgs
          );
        }}
        params={(() => {
          try {
            return {
              centerid: $props.centerId,
              date: $props.date
            };
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return undefined;
            }
            throw e;
          }
        })()}
        ref={ref => {
          $refs["apiGetBookCount"] = ref;
        }}
        url={"https://apigw.paziresh24.com/v1/n8n-nelson/webhook/v1/book-count"}
      />

      <ApiRequest
        data-plasmic-name={"apiGetIncome"}
        data-plasmic-override={overrides.apiGetIncome}
        className={classNames("__wab_instance", sty.apiGetIncome)}
        errorDisplay={
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__nnN25
            )}
          >
            {"Error fetching data"}
          </div>
        }
        loadingDisplay={
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__bHalM
            )}
          >
            {"Loading..."}
          </div>
        }
        method={"GET"}
        onError={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["apiGetIncome", "error"]).apply(
            null,
            eventArgs
          );
        }}
        onLoading={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["apiGetIncome", "loading"]).apply(
            null,
            eventArgs
          );
        }}
        onSuccess={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["apiGetIncome", "data"]).apply(
            null,
            eventArgs
          );
        }}
        params={(() => {
          try {
            return {
              centerid: $props.centerId,
              date: $props.date
            };
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return undefined;
            }
            throw e;
          }
        })()}
        ref={ref => {
          $refs["apiGetIncome"] = ref;
        }}
        url={"https://apigw.paziresh24.com/v1/n8n-nelson/webhook/v1/income"}
      />

      <ApiRequest
        data-plasmic-name={"apiGetbalance"}
        data-plasmic-override={overrides.apiGetbalance}
        className={classNames("__wab_instance", sty.apiGetbalance)}
        errorDisplay={
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__cYlE
            )}
          >
            {"Error fetching data"}
          </div>
        }
        loadingDisplay={
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___0Gc8Y
            )}
          >
            {"Loading..."}
          </div>
        }
        method={"GET"}
        onError={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["apiGetbalance", "error"]).apply(
            null,
            eventArgs
          );
        }}
        onLoading={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["apiGetbalance", "loading"]).apply(
            null,
            eventArgs
          );
        }}
        onSuccess={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["apiGetbalance", "data"]).apply(
            null,
            eventArgs
          );
        }}
        ref={ref => {
          $refs["apiGetbalance"] = ref;
        }}
        url={(() => {
          try {
            return `https://apigw.paziresh24.com/katibe/v1/transactions/balance/p24?productid=7&centerid=${$props.centerId}&account=organization`;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return undefined;
            }
            throw e;
          }
        })()}
      />

      <ApiRequest
        data-plasmic-name={"apiGetBalanceOnlineVisit"}
        data-plasmic-override={overrides.apiGetBalanceOnlineVisit}
        className={classNames("__wab_instance", sty.apiGetBalanceOnlineVisit)}
        errorDisplay={
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__vi5Kt
            )}
          >
            {"Error fetching data"}
          </div>
        }
        loadingDisplay={
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__n9Um5
            )}
          >
            {"Loading..."}
          </div>
        }
        method={"GET"}
        onError={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, [
            "apiGetBalanceOnlineVisit",
            "error"
          ]).apply(null, eventArgs);
        }}
        onLoading={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, [
            "apiGetBalanceOnlineVisit",
            "loading"
          ]).apply(null, eventArgs);
        }}
        onSuccess={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, [
            "apiGetBalanceOnlineVisit",
            "data"
          ]).apply(null, eventArgs);
        }}
        ref={ref => {
          $refs["apiGetBalanceOnlineVisit"] = ref;
        }}
        url={(() => {
          try {
            return $props.centerId === "5532"
              ? `https://apigw.paziresh24.com/katibe/v1/transactions/balance/p24`
              : "";
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return undefined;
            }
            throw e;
          }
        })()}
      />

      <ApiRequest
        data-plasmic-name={"apiGetTotalOnlineVisit"}
        data-plasmic-override={overrides.apiGetTotalOnlineVisit}
        className={classNames("__wab_instance", sty.apiGetTotalOnlineVisit)}
        errorDisplay={
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__fXkUc
            )}
          >
            {"Error fetching data"}
          </div>
        }
        loadingDisplay={
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__k5Nlb
            )}
          >
            {"Loading..."}
          </div>
        }
        method={"GET"}
        onError={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, [
            "apiGetTotalOnlineVisit",
            "error"
          ]).apply(null, eventArgs);
        }}
        onLoading={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, [
            "apiGetTotalOnlineVisit",
            "loading"
          ]).apply(null, eventArgs);
        }}
        onSuccess={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, [
            "apiGetTotalOnlineVisit",
            "data"
          ]).apply(null, eventArgs);
        }}
        ref={ref => {
          $refs["apiGetTotalOnlineVisit"] = ref;
        }}
        url={(() => {
          try {
            return $props.centerId === "5532"
              ? `https://apigw.paziresh24.com/katibe/v1/transactions/report/p24`
              : "";
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return undefined;
            }
            throw e;
          }
        })()}
      />

      <ApiRequest
        data-plasmic-name={"apiGetTotal"}
        data-plasmic-override={overrides.apiGetTotal}
        className={classNames("__wab_instance", sty.apiGetTotal)}
        errorDisplay={
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__cBe2K
            )}
          >
            {"Error fetching data"}
          </div>
        }
        loadingDisplay={
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__vwrZx
            )}
          >
            {"Loading..."}
          </div>
        }
        method={"GET"}
        onError={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["apiGetTotal", "error"]).apply(
            null,
            eventArgs
          );
        }}
        onLoading={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["apiGetTotal", "loading"]).apply(
            null,
            eventArgs
          );
        }}
        onSuccess={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["apiGetTotal", "data"]).apply(
            null,
            eventArgs
          );
        }}
        ref={ref => {
          $refs["apiGetTotal"] = ref;
        }}
        url={(() => {
          try {
            return `https://apigw.paziresh24.com/katibe/v1/transactions/report/p24?book_date=&centerid=${$props.centerId}`;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return undefined;
            }
            throw e;
          }
        })()}
      />

      <ApiRequest
        data-plasmic-name={"apiExpectedIncome"}
        data-plasmic-override={overrides.apiExpectedIncome}
        className={classNames("__wab_instance", sty.apiExpectedIncome)}
        errorDisplay={
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___1SaRk
            )}
          >
            {"Error fetching data"}
          </div>
        }
        loadingDisplay={
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__jkjM2
            )}
          >
            {"Loading..."}
          </div>
        }
        method={"GET"}
        onError={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, [
            "apiExpectedIncome",
            "error"
          ]).apply(null, eventArgs);
        }}
        onLoading={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, [
            "apiExpectedIncome",
            "loading"
          ]).apply(null, eventArgs);
        }}
        onSuccess={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, [
            "apiExpectedIncome",
            "data"
          ]).apply(null, eventArgs);
        }}
        ref={ref => {
          $refs["apiExpectedIncome"] = ref;
        }}
        url={(() => {
          try {
            return $props.centerId !== "5532"
              ? `https://apigw.paziresh24.com/katibe/v1/transactions/balance/p24?productid=7&centerid=${$props.centerId}&account=escrow`
              : `https://apigw.paziresh24.com/katibe/v1/transactions/balance/p24?account=escrow`;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return undefined;
            }
            throw e;
          }
        })()}
      />

      <div className={classNames(projectcss.all, sty.freeBox__kYuwF)}>
        <div
          data-plasmic-name={"bookcount"}
          data-plasmic-override={overrides.bookcount}
          className={classNames(projectcss.all, sty.bookcount)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__evEyR
            )}
          >
            {
              "\u062a\u0639\u062f\u0627\u062f \u0646\u0648\u0628\u062a \u0627\u0645\u0631\u0648\u0632"
            }
          </div>
          {(() => {
            try {
              return $state.apiGetBookCount.data.CountOfBook !== undefined;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return false;
              }
              throw e;
            }
          })() ? (
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__b3Aos
              )}
            >
              <React.Fragment>
                {(() => {
                  try {
                    return `${$state.apiGetBookCount.data.CountOfBook} نوبت`;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "\u062a\u0639\u062f\u0627\u062f \u0646\u0648\u0628\u062a \u0627\u0645\u0631\u0648\u0632";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
          ) : null}
        </div>
        <div
          data-plasmic-name={"balance"}
          data-plasmic-override={overrides.balance}
          className={classNames(projectcss.all, sty.balance)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__dalvH
            )}
          >
            {
              "\u0645\u0648\u062c\u0648\u062f\u06cc \u0642\u0627\u0628\u0644 \u0628\u0631\u062f\u0627\u0634\u062a"
            }
          </div>
          {(() => {
            try {
              return (
                $state.apiGetbalance.data.data.balance !== undefined &&
                $props.centerId != 5532
              );
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return false;
              }
              throw e;
            }
          })() ? (
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__z2Vk5
              )}
            >
              <React.Fragment>
                {(() => {
                  try {
                    return (
                      new Intl.NumberFormat("fa-IR").format(
                        $state.apiGetbalance.data.data.balance / 10
                      ) + " تومان"
                    );
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "\u0645\u0648\u062c\u0648\u062f\u06cc";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
          ) : null}
          {(() => {
            try {
              return (
                $state.apiGetbalance.data.data.balance !== undefined &&
                $props.centerId == 5532
              );
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return false;
              }
              throw e;
            }
          })() ? (
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__wU7FH
              )}
            >
              <React.Fragment>
                {(() => {
                  try {
                    return (
                      new Intl.NumberFormat("fa-IR").format(
                        $state.apiGetBalanceOnlineVisit.data.data.balance / 10
                      ) + " تومان"
                    );
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "0 \u062a\u0648\u0645\u0627\u0646";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
          ) : null}
          {(() => {
            try {
              return (
                ($props.centerId == "5532"
                  ? $state.apiGetBalanceOnlineVisit.data?.data?.balance
                  : $state.apiGetbalance.data.data.balance) > 0
              );
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <div className={classNames(projectcss.all, sty.freeBox__kBu21)}>
              <Dialog
                data-plasmic-name={"dialogTransfer"}
                data-plasmic-override={overrides.dialogTransfer}
                body={
                  <TransferToAnotherWallet
                    data-plasmic-name={"transferToAnotherWallet"}
                    data-plasmic-override={overrides.transferToAnotherWallet}
                    className={classNames(
                      "__wab_instance",
                      sty.transferToAnotherWallet
                    )}
                    onTransferCenteridChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "transferToAnotherWallet",
                        "transferCenterid"
                      ]).apply(null, eventArgs);

                      if (
                        eventArgs.length > 1 &&
                        eventArgs[1] &&
                        eventArgs[1]._plasmic_state_init_
                      ) {
                        return;
                      }
                    }}
                    onTransferedCountChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "transferToAnotherWallet",
                        "transferedCount"
                      ]).apply(null, eventArgs);

                      if (
                        eventArgs.length > 1 &&
                        eventArgs[1] &&
                        eventArgs[1]._plasmic_state_init_
                      ) {
                        return;
                      }
                    }}
                    transferCenterid={generateStateValueProp($state, [
                      "transferToAnotherWallet",
                      "transferCenterid"
                    ])}
                    transferEvent={async () => {
                      const $steps = {};

                      $steps["closeDialog"] = true
                        ? (() => {
                            const actionArgs = {
                              customFunction: async () => {
                                return ($state.dialogTransfer.open = false);
                              }
                            };
                            return (({ customFunction }) => {
                              return customFunction();
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["closeDialog"] != null &&
                        typeof $steps["closeDialog"] === "object" &&
                        typeof $steps["closeDialog"].then === "function"
                      ) {
                        $steps["closeDialog"] = await $steps["closeDialog"];
                      }
                    }}
                  />
                }
                className={classNames("__wab_instance", sty.dialogTransfer)}
                onOpenChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "dialogTransfer",
                    "open"
                  ]).apply(null, eventArgs);

                  if (
                    eventArgs.length > 1 &&
                    eventArgs[1] &&
                    eventArgs[1]._plasmic_state_init_
                  ) {
                    return;
                  }
                }}
                open={generateStateValueProp($state, [
                  "dialogTransfer",
                  "open"
                ])}
                title={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sqlc8
                    )}
                  >
                    {
                      "\u0627\u0646\u062a\u0642\u0627\u0644 \u0648\u062c\u0647 \u0628\u0647 \u06a9\u0627\u0631\u0628\u0631 \u062f\u06cc\u06af\u0631"
                    }
                  </div>
                }
                trigger={
                  <Button
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    children2={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___4WV6S
                        )}
                      >
                        {
                          "\u0627\u0646\u062a\u0642\u0627\u0644 \u0648\u062c\u0640\u0640\u0647"
                        }
                      </div>
                    }
                    className={classNames("__wab_instance", sty.button)}
                    size={"compact"}
                  />
                }
              />

              <Dialog
                data-plasmic-name={"dialogSettlement"}
                data-plasmic-override={overrides.dialogSettlement}
                body={
                  <Settlement
                    data-plasmic-name={"settlement"}
                    data-plasmic-override={overrides.settlement}
                    balance={(() => {
                      try {
                        return $props.centerId == "5532"
                          ? $state.apiGetBalanceOnlineVisit.data?.data?.balance
                          : $state.apiGetbalance.data.data.balance;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                    className={classNames("__wab_instance", sty.settlement)}
                    currentAccointId={(() => {
                      try {
                        return $props.centerId;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                    currentAccountType={(() => {
                      try {
                        return $props.centerId == "5532" ? "" : "centerid";
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                    onSettlement={async () => {
                      const $steps = {};

                      $steps["updateDialogSettlementOpen"] = true
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["dialogSettlement", "open"]
                              },
                              operation: 0,
                              value: false
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;

                              $stateSet(objRoot, variablePath, value);
                              return value;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updateDialogSettlementOpen"] != null &&
                        typeof $steps["updateDialogSettlementOpen"] ===
                          "object" &&
                        typeof $steps["updateDialogSettlementOpen"].then ===
                          "function"
                      ) {
                        $steps["updateDialogSettlementOpen"] =
                          await $steps["updateDialogSettlementOpen"];
                      }

                      $steps["runActionOnApiGetbalance"] =
                        $props.centerId != "5532"
                          ? (() => {
                              const actionArgs = {
                                tplRef: "apiGetbalance",
                                action: "refresh"
                              };
                              return (({ tplRef, action, args }) => {
                                return $refs?.[tplRef]?.[action]?.(
                                  ...(args ?? [])
                                );
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                      if (
                        $steps["runActionOnApiGetbalance"] != null &&
                        typeof $steps["runActionOnApiGetbalance"] ===
                          "object" &&
                        typeof $steps["runActionOnApiGetbalance"].then ===
                          "function"
                      ) {
                        $steps["runActionOnApiGetbalance"] =
                          await $steps["runActionOnApiGetbalance"];
                      }

                      $steps["runActionOnApiGetBalanceOnlineVisit"] =
                        $props.centerId == "5532"
                          ? (() => {
                              const actionArgs = {
                                tplRef: "apiGetBalanceOnlineVisit",
                                action: "refresh"
                              };
                              return (({ tplRef, action, args }) => {
                                return $refs?.[tplRef]?.[action]?.(
                                  ...(args ?? [])
                                );
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                      if (
                        $steps["runActionOnApiGetBalanceOnlineVisit"] != null &&
                        typeof $steps["runActionOnApiGetBalanceOnlineVisit"] ===
                          "object" &&
                        typeof $steps["runActionOnApiGetBalanceOnlineVisit"]
                          .then === "function"
                      ) {
                        $steps["runActionOnApiGetBalanceOnlineVisit"] =
                          await $steps["runActionOnApiGetBalanceOnlineVisit"];
                      }
                    }}
                  />
                }
                className={classNames("__wab_instance", sty.dialogSettlement)}
                onOpenChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "dialogSettlement",
                    "open"
                  ]).apply(null, eventArgs);

                  if (
                    eventArgs.length > 1 &&
                    eventArgs[1] &&
                    eventArgs[1]._plasmic_state_init_
                  ) {
                    return;
                  }
                }}
                open={generateStateValueProp($state, [
                  "dialogSettlement",
                  "open"
                ])}
                title={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zAvKa
                    )}
                  >
                    {
                      "\u062f\u0631\u062e\u0648\u0627\u0633\u062a \u062a\u0633\u0648\u06cc\u0647 \u062d\u0633\u0627\u0628"
                    }
                  </div>
                }
                trigger={
                  <Button
                    data-plasmic-name={"btnSettlement"}
                    data-plasmic-override={overrides.btnSettlement}
                    children2={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__y4Il3
                        )}
                      >
                        {
                          "\u062f\u0631\u062e\u0648\u0627\u0633\u062a \u062a\u0633\u0648\u06cc\u0647"
                        }
                      </div>
                    }
                    className={classNames("__wab_instance", sty.btnSettlement)}
                    color={"green"}
                    size={"compact"}
                  />
                }
              />
            </div>
          ) : null}
        </div>
        {(() => {
          try {
            return $props.centerId != "5532";
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return true;
            }
            throw e;
          }
        })() ? (
          <div
            data-plasmic-name={"balance2"}
            data-plasmic-override={overrides.balance2}
            className={classNames(projectcss.all, sty.balance2)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__slqAu
              )}
            >
              {
                "\u0645\u0648\u062c\u0648\u062f\u06cc \u062f\u0631 \u0627\u0646\u062a\u0638\u0627\u0631"
              }
            </div>
            {(() => {
              try {
                return (
                  $state.apiGetbalance.data.data.balance !== undefined &&
                  $props.centerId != 5532
                );
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return false;
                }
                throw e;
              }
            })() ? (
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__nZLzB
                )}
              >
                <React.Fragment>
                  {(() => {
                    try {
                      return (
                        new Intl.NumberFormat("fa-IR").format(
                          $state.apiExpectedIncome.data.data.balance / 10
                        ) + " تومان"
                      );
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return "\u0645\u0648\u062c\u0648\u062f\u06cc";
                      }
                      throw e;
                    }
                  })()}
                </React.Fragment>
              </div>
            ) : null}
            {(() => {
              try {
                return (
                  $state.apiGetbalance.data.data.balance !== undefined &&
                  $props.centerId == 5532
                );
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return false;
                }
                throw e;
              }
            })() ? (
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__smq6C
                )}
              >
                <React.Fragment>
                  {(() => {
                    try {
                      return (
                        new Intl.NumberFormat("fa-IR").format(
                          $state.apiExpectedIncome.data.data.balance / 10
                        ) + " تومان"
                      );
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return "\u0645\u0648\u062c\u0648\u062f\u06cc";
                      }
                      throw e;
                    }
                  })()}
                </React.Fragment>
              </div>
            ) : null}
          </div>
        ) : null}
        <div
          data-plasmic-name={"income"}
          data-plasmic-override={overrides.income}
          className={classNames(projectcss.all, sty.income)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__ghfTz
            )}
          >
            {
              "\u062f\u0631\u0622\u0645\u062f \u0627\u0645\u0631\u0648\u0632 \u062a\u0627 \u0627\u06cc\u0646 \u0644\u062d\u0638\u0647"
            }
          </div>
          {(() => {
            try {
              return $state.apiGetIncome.data.sum_cost !== undefined;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return false;
              }
              throw e;
            }
          })() ? (
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__r7Erz
              )}
            >
              <React.Fragment>
                {(() => {
                  try {
                    return (
                      new Intl.NumberFormat("fa-IR").format(
                        $state.apiGetIncome.data.sum_cost / 10
                      ) + " تومان"
                    );
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "0 \u062a\u0648\u0645\u0627\u0646";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
          ) : null}
        </div>
        <div
          data-plasmic-name={"totalincome"}
          data-plasmic-override={overrides.totalincome}
          className={classNames(projectcss.all, sty.totalincome)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__blbe
            )}
          >
            {
              "\u06a9\u0644 \u062f\u0631\u0627\u0645\u062f \u0627\u0632 \u0634\u0631\u0648\u0639 \u0647\u0645\u06a9\u0627\u0631\u06cc"
            }
          </div>
          {(() => {
            try {
              return $props.centerId != 5532;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return false;
              }
              throw e;
            }
          })() ? (
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__dmh0V
              )}
            >
              <React.Fragment>
                {(() => {
                  try {
                    return $state.apiGetTotal.error === null
                      ? new Intl.NumberFormat("fa-IR").format(
                          $state.apiGetTotal.data.data.deposit / 10
                        ) + " تومان"
                      : 0 + " تومان";
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "\u06a9\u0644 \u062f\u0631\u0627\u0645\u062f \u0627\u0632 \u0634\u0631\u0648\u0639 \u0647\u0645\u06a9\u0627\u0631\u06cc";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
          ) : null}
          {(() => {
            try {
              return $props.centerId == 5532;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return false;
              }
              throw e;
            }
          })() ? (
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ulU7
              )}
            >
              <React.Fragment>
                {(() => {
                  try {
                    return $state.apiGetTotalOnlineVisit.error === null
                      ? new Intl.NumberFormat("fa-IR").format(
                          $state.apiGetTotalOnlineVisit.data.data.deposit / 10
                        ) + " تومان"
                      : 0 + " تومان";
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "0 \u062a\u0648\u0645\u0627\u0646";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
          ) : null}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "apiGetBookCount",
    "apiGetIncome",
    "apiGetbalance",
    "apiGetBalanceOnlineVisit",
    "apiGetTotalOnlineVisit",
    "apiGetTotal",
    "apiExpectedIncome",
    "bookcount",
    "balance",
    "dialogTransfer",
    "button",
    "transferToAnotherWallet",
    "dialogSettlement",
    "btnSettlement",
    "settlement",
    "balance2",
    "income",
    "totalincome"
  ],
  apiGetBookCount: ["apiGetBookCount"],
  apiGetIncome: ["apiGetIncome"],
  apiGetbalance: ["apiGetbalance"],
  apiGetBalanceOnlineVisit: ["apiGetBalanceOnlineVisit"],
  apiGetTotalOnlineVisit: ["apiGetTotalOnlineVisit"],
  apiGetTotal: ["apiGetTotal"],
  apiExpectedIncome: ["apiExpectedIncome"],
  bookcount: ["bookcount"],
  balance: [
    "balance",
    "dialogTransfer",
    "button",
    "transferToAnotherWallet",
    "dialogSettlement",
    "btnSettlement",
    "settlement"
  ],
  dialogTransfer: ["dialogTransfer", "button", "transferToAnotherWallet"],
  button: ["button"],
  transferToAnotherWallet: ["transferToAnotherWallet"],
  dialogSettlement: ["dialogSettlement", "btnSettlement", "settlement"],
  btnSettlement: ["btnSettlement"],
  settlement: ["settlement"],
  balance2: ["balance2"],
  income: ["income"],
  totalincome: ["totalincome"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  apiGetBookCount: typeof ApiRequest;
  apiGetIncome: typeof ApiRequest;
  apiGetbalance: typeof ApiRequest;
  apiGetBalanceOnlineVisit: typeof ApiRequest;
  apiGetTotalOnlineVisit: typeof ApiRequest;
  apiGetTotal: typeof ApiRequest;
  apiExpectedIncome: typeof ApiRequest;
  bookcount: "div";
  balance: "div";
  dialogTransfer: typeof Dialog;
  button: typeof Button;
  transferToAnotherWallet: typeof TransferToAnotherWallet;
  dialogSettlement: typeof Dialog;
  btnSettlement: typeof Button;
  settlement: typeof Settlement;
  balance2: "div";
  income: "div";
  totalincome: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFinancialReports__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFinancialReports__VariantsArgs;
    args?: PlasmicFinancialReports__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicFinancialReports__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicFinancialReports__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFinancialReports__ArgProps,
          internalVariantPropNames: PlasmicFinancialReports__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFinancialReports__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFinancialReports";
  } else {
    func.displayName = `PlasmicFinancialReports.${nodeName}`;
  }
  return func;
}

export const PlasmicFinancialReports = Object.assign(
  // Top-level PlasmicFinancialReports renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    apiGetBookCount: makeNodeComponent("apiGetBookCount"),
    apiGetIncome: makeNodeComponent("apiGetIncome"),
    apiGetbalance: makeNodeComponent("apiGetbalance"),
    apiGetBalanceOnlineVisit: makeNodeComponent("apiGetBalanceOnlineVisit"),
    apiGetTotalOnlineVisit: makeNodeComponent("apiGetTotalOnlineVisit"),
    apiGetTotal: makeNodeComponent("apiGetTotal"),
    apiExpectedIncome: makeNodeComponent("apiExpectedIncome"),
    bookcount: makeNodeComponent("bookcount"),
    balance: makeNodeComponent("balance"),
    dialogTransfer: makeNodeComponent("dialogTransfer"),
    button: makeNodeComponent("button"),
    transferToAnotherWallet: makeNodeComponent("transferToAnotherWallet"),
    dialogSettlement: makeNodeComponent("dialogSettlement"),
    btnSettlement: makeNodeComponent("btnSettlement"),
    settlement: makeNodeComponent("settlement"),
    balance2: makeNodeComponent("balance2"),
    income: makeNodeComponent("income"),
    totalincome: makeNodeComponent("totalincome"),

    // Metadata about props expected for PlasmicFinancialReports
    internalVariantProps: PlasmicFinancialReports__VariantProps,
    internalArgProps: PlasmicFinancialReports__ArgProps
  }
);

export default PlasmicFinancialReports;
/* prettier-ignore-end */
