/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oFMww5CfyAzvgggjKwbJid
// Component: 1Tzg-xPJwovd

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import TextInput from "../../TextInput"; // plasmic-import: ecH5hyIcrDOH/component
import { ApiRequest } from "@/fragment/components/api-request"; // plasmic-import: 1e0q7f6tCMQt/codeComponent
import Button from "../../Button"; // plasmic-import: oVzoHzMf1TLl/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: oFMww5CfyAzvgggjKwbJid/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: oFMww5CfyAzvgggjKwbJid/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: oFMww5CfyAzvgggjKwbJid/projectcss
import sty from "./PlasmicSettlement.module.css"; // plasmic-import: 1Tzg-xPJwovd/css

import SearchSvgIcon from "./icons/PlasmicIcon__SearchSvg"; // plasmic-import: JgTy3dPZfpTf/icon
import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: wUFirrLIL74U/icon
import ChevronRightIcon from "../fragment_icons/icons/PlasmicIcon__ChevronRight"; // plasmic-import: GHdF3hS-oP_3/icon
import ChevronLeftIcon from "../fragment_icons/icons/PlasmicIcon__ChevronLeft"; // plasmic-import: r9Upp9NbiZkf/icon

createPlasmicElementProxy;

export type PlasmicSettlement__VariantMembers = {};
export type PlasmicSettlement__VariantsArgs = {};
type VariantPropType = keyof PlasmicSettlement__VariantsArgs;
export const PlasmicSettlement__VariantProps = new Array<VariantPropType>();

export type PlasmicSettlement__ArgsType = {
  balance?: number;
  currentAccountType?: string;
  currentAccointId?: string;
  onSettlement?: () => void;
};
type ArgPropType = keyof PlasmicSettlement__ArgsType;
export const PlasmicSettlement__ArgProps = new Array<ArgPropType>(
  "balance",
  "currentAccountType",
  "currentAccointId",
  "onSettlement"
);

export type PlasmicSettlement__OverridesType = {
  root?: Flex__<"div">;
  txtSettlemenAmount?: Flex__<typeof TextInput>;
  apiRequest?: Flex__<typeof ApiRequest>;
  txtCardNumber?: Flex__<typeof TextInput>;
};

export interface DefaultSettlementProps {
  balance?: number;
  currentAccountType?: string;
  currentAccointId?: string;
  onSettlement?: () => void;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSettlement__RenderFunc(props: {
  variants: PlasmicSettlement__VariantsArgs;
  args: PlasmicSettlement__ArgsType;
  overrides: PlasmicSettlement__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const $globalActions = useGlobalActions?.();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "txtSettlemenAmount.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $props.balance;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      },
      {
        path: "txtCardNumber.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "apiRequest.data",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiRequest"
      },
      {
        path: "apiRequest.error",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiRequest"
      },
      {
        path: "apiRequest.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiRequest"
      },
      {
        path: "isLoadingButton",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__r80Vs)}>
        <div className={classNames(projectcss.all, sty.freeBox__t0Rh)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__lEhl6
            )}
          >
            {"\u0645\u0628\u0644\u063a:"}
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__e3IM3)}>
          <TextInput
            data-plasmic-name={"txtSettlemenAmount"}
            data-plasmic-override={overrides.txtSettlemenAmount}
            className={classNames("__wab_instance", sty.txtSettlemenAmount)}
            onChange={async (...eventArgs: any) => {
              ((...eventArgs) => {
                generateStateOnChangeProp($state, [
                  "txtSettlemenAmount",
                  "value"
                ])((e => e.target?.value).apply(null, eventArgs));
              }).apply(null, eventArgs);

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }

              (async event => {
                const $steps = {};
              }).apply(null, eventArgs);
            }}
            placeholder={
              "\u0645\u0628\u0644\u063a \u0645\u0648\u0631\u062f \u0646\u0638\u0631 \u0628\u0647 \u0631\u06cc\u0627\u0644"
            }
            type={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "number"
                : undefined
            }
            value={
              generateStateValueProp($state, ["txtSettlemenAmount", "value"]) ??
              ""
            }
          />
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__eyJiv)}>
        <div className={classNames(projectcss.all, sty.freeBox__kjja3)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__voq2J
            )}
          >
            {"\u0634\u0645\u0627\u0631\u0647 \u06a9\u0627\u0631\u062a:"}
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__j3Gan)}>
          <ApiRequest
            data-plasmic-name={"apiRequest"}
            data-plasmic-override={overrides.apiRequest}
            className={classNames("__wab_instance", sty.apiRequest)}
            errorDisplay={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___0ZvXk
                )}
              >
                {"Error fetching data"}
              </div>
            }
            loadingDisplay={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___9F1N0
                )}
              >
                {"Loading..."}
              </div>
            }
            method={"GET"}
            onError={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["apiRequest", "error"]).apply(
                null,
                eventArgs
              );
            }}
            onLoading={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, [
                "apiRequest",
                "loading"
              ]).apply(null, eventArgs);
            }}
            onSuccess={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["apiRequest", "data"]).apply(
                null,
                eventArgs
              );
            }}
            ref={ref => {
              $refs["apiRequest"] = ref;
            }}
            url={(() => {
              try {
                return (() => {
                  if ($props.currentAccountType == "centerid")
                    return (
                      "https://apigw.paziresh24.com/financialaccount/v1/useraccounts?centerid=" +
                      $props.currentAccointId
                    );
                  else
                    return "https://apigw.paziresh24.com/financialaccount/v1/useraccounts";
                })();
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return undefined;
                }
                throw e;
              }
            })()}
          >
            {(() => {
              try {
                return $state.apiRequest.data.data?.length == 0;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <TextInput
                data-plasmic-name={"txtCardNumber"}
                data-plasmic-override={overrides.txtCardNumber}
                autoFocus={true}
                className={classNames("__wab_instance", sty.txtCardNumber)}
                onChange={async (...eventArgs: any) => {
                  ((...eventArgs) => {
                    generateStateOnChangeProp($state, [
                      "txtCardNumber",
                      "value"
                    ])((e => e.target?.value).apply(null, eventArgs));
                  }).apply(null, eventArgs);

                  if (
                    eventArgs.length > 1 &&
                    eventArgs[1] &&
                    eventArgs[1]._plasmic_state_init_
                  ) {
                    return;
                  }
                }}
                placeholder={
                  "\u0634\u0645\u0627\u0631\u0647 \u06a9\u0627\u0631\u062a \u0631\u0627 \u0648\u0627\u0631\u062f \u06a9\u0646\u06cc\u062f (\u063a\u06cc\u0631 \u0627\u0632 \u0628\u0644\u0648 \u0628\u0627\u0646\u06a9)"
                }
                value={
                  generateStateValueProp($state, ["txtCardNumber", "value"]) ??
                  ""
                }
              />
            ) : null}
            {(() => {
              try {
                return $state.apiRequest.data.data?.length > 0;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div className={classNames(projectcss.all, sty.freeBox__bxkmu)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__iEwVb
                  )}
                >
                  <React.Fragment>
                    {(() => {
                      try {
                        return (
                          $state.apiRequest.data.data[0].name +
                          " - " +
                          ($state.apiRequest?.data?.data?.[0]?.cardid
                            ? $state.apiRequest.data.data[0].cardid
                            : $state.apiRequest.data.data?.[0]?.iban)
                        );
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "";
                        }
                        throw e;
                      }
                    })()}
                  </React.Fragment>
                </div>
                <Button
                  children2={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mU7U
                      )}
                    >
                      {
                        "\u0645\u062f\u06cc\u0631\u06cc\u062a \u062d\u0633\u0627\u0628"
                      }
                    </div>
                  }
                  className={classNames("__wab_instance", sty.button__jYdSt)}
                  color={"softBlue"}
                  onClick={async event => {
                    const $steps = {};

                    $steps["invokeGlobalAction"] = true
                      ? (() => {
                          const actionArgs = {
                            args: [
                              "https://www.paziresh24.com/dashboard/apps/katibe/setting/"
                            ]
                          };
                          return $globalActions["Hamdast.openLink"]?.apply(
                            null,
                            [...actionArgs.args]
                          );
                        })()
                      : undefined;
                    if (
                      $steps["invokeGlobalAction"] != null &&
                      typeof $steps["invokeGlobalAction"] === "object" &&
                      typeof $steps["invokeGlobalAction"].then === "function"
                    ) {
                      $steps["invokeGlobalAction"] =
                        await $steps["invokeGlobalAction"];
                    }
                  }}
                  size={"minimal"}
                />
              </div>
            ) : null}
          </ApiRequest>
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__md5Re)}>
        <div className={classNames(projectcss.all, sty.freeBox__zoIlu)}>
          <Button
            children2={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bjVlh
                )}
              >
                <React.Fragment>
                  {(() => {
                    try {
                      return (
                        new Intl.NumberFormat("fa-IR").format(
                          $state.txtSettlemenAmount.value
                        ) +
                        " ریال" +
                        " - ثبت درخواست"
                      );
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return "\u062b\u0628\u062a \u062f\u0631\u062e\u0648\u0627\u0633\u062a";
                      }
                      throw e;
                    }
                  })()}
                </React.Fragment>
              </div>
            }
            className={classNames("__wab_instance", sty.button__fyIWn)}
            isDisabled={(() => {
              try {
                return (
                  $state.txtSettlemenAmount.value &&
                  ($state.apiRequest?.data?.data?.length == 0
                    ? $state.txtCardNumber.value?.length != 16
                    : false)
                );
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return [];
                }
                throw e;
              }
            })()}
            loading={(() => {
              try {
                return $state.apiRequest.loading || $state.isLoadingButton;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return [];
                }
                throw e;
              }
            })()}
            onClick={async event => {
              const $steps = {};

              $steps["updateIsLoadingButton"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["isLoadingButton"]
                      },
                      operation: 0,
                      value: true
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateIsLoadingButton"] != null &&
                typeof $steps["updateIsLoadingButton"] === "object" &&
                typeof $steps["updateIsLoadingButton"].then === "function"
              ) {
                $steps["updateIsLoadingButton"] =
                  await $steps["updateIsLoadingButton"];
              }

              $steps["registerCardNumber"] =
                $state.apiRequest.data.data?.length == 0
                  ? (() => {
                      const actionArgs = {
                        args: [
                          "POST",
                          "https://apigw.paziresh24.com/financialaccount/v1/useraccount",
                          undefined,
                          (() => {
                            try {
                              return {
                                cardid: $state.txtCardNumber.value,
                                centerid:
                                  $props.currentAccountType === "centerid"
                                    ? $props.currentAccointId
                                    : ""
                              };
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()
                        ]
                      };
                      return $globalActions["Fragment.apiRequest"]?.apply(
                        null,
                        [...actionArgs.args]
                      );
                    })()
                  : undefined;
              if (
                $steps["registerCardNumber"] != null &&
                typeof $steps["registerCardNumber"] === "object" &&
                typeof $steps["registerCardNumber"].then === "function"
              ) {
                $steps["registerCardNumber"] =
                  await $steps["registerCardNumber"];
              }

              $steps["errorRegisterCardNumberToast"] =
                $steps.registerCardNumber?.status > 0 &&
                $steps.registerCardNumber?.status != 200
                  ? (() => {
                      const actionArgs = {
                        args: [
                          "error",
                          (() => {
                            try {
                              return $steps.registerCardNumber?.data?.message;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })(),
                          "top-center"
                        ]
                      };
                      return $globalActions["Fragment.showToast"]?.apply(null, [
                        ...actionArgs.args
                      ]);
                    })()
                  : undefined;
              if (
                $steps["errorRegisterCardNumberToast"] != null &&
                typeof $steps["errorRegisterCardNumberToast"] === "object" &&
                typeof $steps["errorRegisterCardNumberToast"].then ===
                  "function"
              ) {
                $steps["errorRegisterCardNumberToast"] =
                  await $steps["errorRegisterCardNumberToast"];
              }

              $steps["getUserAccounts"] =
                $steps.registerCardNumber?.status == 200
                  ? (() => {
                      const actionArgs = {
                        args: [
                          undefined,
                          (() => {
                            try {
                              return (() => {
                                if ($props.currentAccountType == "centerid")
                                  return (
                                    "https://apigw.paziresh24.com/financialaccount/v1/useraccounts?centerid=" +
                                    $props.currentAccointId
                                  );
                                else
                                  return "https://apigw.paziresh24.com/financialaccount/v1/useraccounts";
                              })();
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()
                        ]
                      };
                      return $globalActions["Fragment.apiRequest"]?.apply(
                        null,
                        [...actionArgs.args]
                      );
                    })()
                  : undefined;
              if (
                $steps["getUserAccounts"] != null &&
                typeof $steps["getUserAccounts"] === "object" &&
                typeof $steps["getUserAccounts"].then === "function"
              ) {
                $steps["getUserAccounts"] = await $steps["getUserAccounts"];
              }

              $steps["requestSettlement"] =
                !!$state.apiRequest?.data?.data?.[0]?.accountid ||
                !!$steps.getUserAccounts?.data?.data?.[0]?.accountid
                  ? (() => {
                      const actionArgs = {
                        args: [
                          "POST",
                          (() => {
                            try {
                              return "https://apigw.paziresh24.com/ganjname/v1/settlement/saman";
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })(),
                          undefined,
                          (() => {
                            try {
                              return (() => {
                                const accountid =
                                  $state.apiRequest?.data?.data?.[0]
                                    ?.accountid ??
                                  $steps.getUserAccounts?.data?.data?.[0]
                                    ?.accountid;
                                return {
                                  accountid: parseInt(accountid),
                                  amount: parseInt(
                                    $state.txtSettlemenAmount.value
                                  )
                                };
                              })();
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()
                        ]
                      };
                      return $globalActions["Fragment.apiRequest"]?.apply(
                        null,
                        [...actionArgs.args]
                      );
                    })()
                  : undefined;
              if (
                $steps["requestSettlement"] != null &&
                typeof $steps["requestSettlement"] === "object" &&
                typeof $steps["requestSettlement"].then === "function"
              ) {
                $steps["requestSettlement"] = await $steps["requestSettlement"];
              }

              $steps["errorRequestSettlementToast"] =
                $steps.requestSettlement?.status != 200
                  ? (() => {
                      const actionArgs = {
                        args: [
                          "error",
                          (() => {
                            try {
                              return $steps?.requestSettlement?.data?.message;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })(),
                          "top-center"
                        ]
                      };
                      return $globalActions["Fragment.showToast"]?.apply(null, [
                        ...actionArgs.args
                      ]);
                    })()
                  : undefined;
              if (
                $steps["errorRequestSettlementToast"] != null &&
                typeof $steps["errorRequestSettlementToast"] === "object" &&
                typeof $steps["errorRequestSettlementToast"].then === "function"
              ) {
                $steps["errorRequestSettlementToast"] =
                  await $steps["errorRequestSettlementToast"];
              }

              $steps["invokeGlobalAction"] =
                $steps.requestSettlement?.status == 200
                  ? (() => {
                      const actionArgs = {
                        args: [
                          undefined,
                          (() => {
                            try {
                              return $steps?.requestSettlement?.data?.message;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })(),
                          "top-center"
                        ]
                      };
                      return $globalActions["Fragment.showToast"]?.apply(null, [
                        ...actionArgs.args
                      ]);
                    })()
                  : undefined;
              if (
                $steps["invokeGlobalAction"] != null &&
                typeof $steps["invokeGlobalAction"] === "object" &&
                typeof $steps["invokeGlobalAction"].then === "function"
              ) {
                $steps["invokeGlobalAction"] =
                  await $steps["invokeGlobalAction"];
              }

              $steps["runOnSettlement"] =
                $steps.requestSettlement?.status == 200
                  ? (() => {
                      const actionArgs = { eventRef: $props["onSettlement"] };
                      return (({ eventRef, args }) => {
                        return eventRef?.(...(args ?? []));
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
              if (
                $steps["runOnSettlement"] != null &&
                typeof $steps["runOnSettlement"] === "object" &&
                typeof $steps["runOnSettlement"].then === "function"
              ) {
                $steps["runOnSettlement"] = await $steps["runOnSettlement"];
              }

              $steps["updateIsLoadingButton2"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["isLoadingButton"]
                      },
                      operation: 0,
                      value: false
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateIsLoadingButton2"] != null &&
                typeof $steps["updateIsLoadingButton2"] === "object" &&
                typeof $steps["updateIsLoadingButton2"].then === "function"
              ) {
                $steps["updateIsLoadingButton2"] =
                  await $steps["updateIsLoadingButton2"];
              }
            }}
            size={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "compact"
                : undefined
            }
          />
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "txtSettlemenAmount", "apiRequest", "txtCardNumber"],
  txtSettlemenAmount: ["txtSettlemenAmount"],
  apiRequest: ["apiRequest", "txtCardNumber"],
  txtCardNumber: ["txtCardNumber"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  txtSettlemenAmount: typeof TextInput;
  apiRequest: typeof ApiRequest;
  txtCardNumber: typeof TextInput;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSettlement__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSettlement__VariantsArgs;
    args?: PlasmicSettlement__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicSettlement__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicSettlement__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSettlement__ArgProps,
          internalVariantPropNames: PlasmicSettlement__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSettlement__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSettlement";
  } else {
    func.displayName = `PlasmicSettlement.${nodeName}`;
  }
  return func;
}

export const PlasmicSettlement = Object.assign(
  // Top-level PlasmicSettlement renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    txtSettlemenAmount: makeNodeComponent("txtSettlemenAmount"),
    apiRequest: makeNodeComponent("apiRequest"),
    txtCardNumber: makeNodeComponent("txtCardNumber"),

    // Metadata about props expected for PlasmicSettlement
    internalVariantProps: PlasmicSettlement__VariantProps,
    internalArgProps: PlasmicSettlement__ArgProps
  }
);

export default PlasmicSettlement;
/* prettier-ignore-end */
